name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Format
        run: cargo fmt --check
      - name: Test
        run: cargo test --all-targets
      - name: Feature Check CUDA
        run: cargo check --all-targets --features cuda

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Feature Check Metal
        run: cargo check --all-targets --features metal
